FROM golang:1.21-alpine AS builder

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum main.go ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/app ./...

FROM alpine:latest
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .
CMD ["app"]