version: '3'

services:
  laravel:
    build: 
      context: ./colocando-em-pratica/laravel
      dockerfile: Dockerfile.prod
    image: juliop3p/laravel:prod
    container_name: laravel
    networks:
      - laranet
  
  nginx: 
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: juliop3p/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports: 
      - "8080:80"

networks:
  laranet:
    driver: bridge